#pragma once

#include <memory>
#include <string>
#include <vector>
#include <stdexcept>
#include <mutex>
#include <cassert>
#include <fstream>
#include <iostream>
#include <algorithm>
#include <set>
#include <thread>
#include <unordered_map>
#include <chrono>
#include <cmath>
#include <concepts>
#include <optional>
#include <cstddef>
#include <cstdlib>
#include <type_traits>
#include <future>
#include <condition_variable>
#include <queue>
#include <functional>
#include <ranges>
#include <numeric>